version: "3.8"
services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - ./db/.env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.222.0/24
