services:
  db:
    image: postgres
    container_name: db
    env_file:
      - ./db/.env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    build: ./server
    container_name: server
    env_file:
      - ./server/.env
    volumes:
      - ./server/src:/app/src
      - /app/node_modules
    ports:
      - 3333:3333
    depends_on:
      - db

volumes:
  db_data:

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.222.0/24
