services:
  db:
    image: postgres
    container_name: db
    env_file:
      - ./db/.env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: server
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 3333:3333
    depends_on:
      - db
  
  client:
    build: ./client
    container_name: client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - server

volumes:
  db_data:
