services:
  db:
    image: postgres
    container_name: db
    env_file:
      - ./db/.env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    build: ./server
    container_name: server
    env_file:
      - ./server/.env
    volumes:
      - ./server/src:/app/src
      - /app/node_modules
      # Why do the named volumes below won't work?
      # - /app/package.json
      # - /app/package-lock.json
    ports:
      - 3333:3333
    depends_on:
      - db
  
  client:
    build: ./client
    container_name: client
    volumes:
      - ./client:/app
      - /app/node_modules
      # - /app/package.json
      # - /app/package-lock.json
    ports:
      - 3000:3000
    depends_on:
      - server

volumes:
  db_data:

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.222.0/24
